using FBEECSEE.Library.impl;
using NUnit.Framework;

namespace FBEECSEE.Library.Tests.impl;

[TestFixture]
public class LoopEnumerationFactoryTests
{
    private LoopEnumerationFactory _cut = null!;

    [SetUp]
    public void SetUp()
    {
        _cut = new LoopEnumerationFactory();
    }

    [Test]
    public void CreateLoopEnumeration_ReturnsConfiguredRange()
    {
        var values = _cut.CreateLoopEnumeration().ToArray();

        Assert.That(values, Is.EqualTo(Enumerable.Range(Constants.START_LOOP_VALUE, Constants.MAXIMUM_LOOP_VALUE)));
        Assert.That(values.Length, Is.EqualTo(Constants.MAXIMUM_LOOP_VALUE));
        Assert.That(values.First(), Is.EqualTo(Constants.START_LOOP_VALUE));
        Assert.That(values.Last(), Is.EqualTo(Constants.START_LOOP_VALUE + Constants.MAXIMUM_LOOP_VALUE - 1));
    }


    [TestCase(0, LoopEnumerationFactory.Numbers.One)]
    [TestCase(1, LoopEnumerationFactory.Numbers.Two)]
    [TestCase(2, LoopEnumerationFactory.Numbers.Three)]
    [TestCase(3, LoopEnumerationFactory.Numbers.Four)]
    [TestCase(4, LoopEnumerationFactory.Numbers.Five)]
    [TestCase(5, LoopEnumerationFactory.Numbers.Six)]
    [TestCase(6, LoopEnumerationFactory.Numbers.Seven)]
    [TestCase(7, LoopEnumerationFactory.Numbers.Eight)]
    [TestCase(8, LoopEnumerationFactory.Numbers.Nine)]
    [TestCase(9, LoopEnumerationFactory.Numbers.Ten)]
    [TestCase(10, LoopEnumerationFactory.Numbers.Eleven)]
    [TestCase(11, LoopEnumerationFactory.Numbers.Twelve)]
    [TestCase(12, LoopEnumerationFactory.Numbers.Thirteen)]
    [TestCase(13, LoopEnumerationFactory.Numbers.Fourteen)]
    [TestCase(14, LoopEnumerationFactory.Numbers.Fifteen)]
    [TestCase(15, LoopEnumerationFactory.Numbers.Sixteen)]
    [TestCase(16, LoopEnumerationFactory.Numbers.Seventeen)]
    [TestCase(17, LoopEnumerationFactory.Numbers.Eighteen)]
    [TestCase(18, LoopEnumerationFactory.Numbers.Nineteen)]
    [TestCase(19, LoopEnumerationFactory.Numbers.Twenty)]
    [TestCase(20, LoopEnumerationFactory.Numbers.TwentyOne)]
    [TestCase(21, LoopEnumerationFactory.Numbers.TwentyTwo)]
    [TestCase(22, LoopEnumerationFactory.Numbers.TwentyThree)]
    [TestCase(23, LoopEnumerationFactory.Numbers.TwentyFour)]
    [TestCase(24, LoopEnumerationFactory.Numbers.TwentyFive)]
    [TestCase(25, LoopEnumerationFactory.Numbers.TwentySix)]
    [TestCase(26, LoopEnumerationFactory.Numbers.TwentySeven)]
    [TestCase(27, LoopEnumerationFactory.Numbers.TwentyEight)]
    [TestCase(28, LoopEnumerationFactory.Numbers.TwentyNine)]
    [TestCase(29, LoopEnumerationFactory.Numbers.Thirty)]
    [TestCase(30, LoopEnumerationFactory.Numbers.ThirtyOne)]
    [TestCase(31, LoopEnumerationFactory.Numbers.ThirtyTwo)]
    [TestCase(32, LoopEnumerationFactory.Numbers.ThirtyThree)]
    [TestCase(33, LoopEnumerationFactory.Numbers.ThirtyFour)]
    [TestCase(34, LoopEnumerationFactory.Numbers.ThirtyFive)]
    [TestCase(35, LoopEnumerationFactory.Numbers.ThirtySix)]
    [TestCase(36, LoopEnumerationFactory.Numbers.ThirtySeven)]
    [TestCase(37, LoopEnumerationFactory.Numbers.ThirtyEight)]
    [TestCase(38, LoopEnumerationFactory.Numbers.ThirtyNine)]
    [TestCase(39, LoopEnumerationFactory.Numbers.Forty)]
    [TestCase(40, LoopEnumerationFactory.Numbers.FortyOne)]
    [TestCase(41, LoopEnumerationFactory.Numbers.FortyTwo)]
    [TestCase(42, LoopEnumerationFactory.Numbers.FortyThree)]
    [TestCase(43, LoopEnumerationFactory.Numbers.FortyFour)]
    [TestCase(44, LoopEnumerationFactory.Numbers.FortyFive)]
    [TestCase(45, LoopEnumerationFactory.Numbers.FortySix)]
    [TestCase(46, LoopEnumerationFactory.Numbers.FortySeven)]
    [TestCase(47, LoopEnumerationFactory.Numbers.FortyEight)]
    [TestCase(48, LoopEnumerationFactory.Numbers.FortyNine)]
    [TestCase(49, LoopEnumerationFactory.Numbers.Fifty)]
    [TestCase(50, LoopEnumerationFactory.Numbers.FiftyOne)]
    [TestCase(51, LoopEnumerationFactory.Numbers.FiftyTwo)]
    [TestCase(52, LoopEnumerationFactory.Numbers.FiftyThree)]
    [TestCase(53, LoopEnumerationFactory.Numbers.FiftyFour)]
    [TestCase(54, LoopEnumerationFactory.Numbers.FiftyFive)]
    [TestCase(55, LoopEnumerationFactory.Numbers.FiftySix)]
    [TestCase(56, LoopEnumerationFactory.Numbers.FiftySeven)]
    [TestCase(57, LoopEnumerationFactory.Numbers.FiftyEight)]
    [TestCase(58, LoopEnumerationFactory.Numbers.FiftyNine)]
    [TestCase(59, LoopEnumerationFactory.Numbers.Sixty)]
    [TestCase(60, LoopEnumerationFactory.Numbers.SixtyOne)]
    [TestCase(61, LoopEnumerationFactory.Numbers.SixtyTwo)]
    [TestCase(62, LoopEnumerationFactory.Numbers.SixtyThree)]
    [TestCase(63, LoopEnumerationFactory.Numbers.SixtyFour)]
    [TestCase(64, LoopEnumerationFactory.Numbers.SixtyFive)]
    [TestCase(65, LoopEnumerationFactory.Numbers.SixtySix)]
    [TestCase(66, LoopEnumerationFactory.Numbers.SixtySeven)]
    [TestCase(67, LoopEnumerationFactory.Numbers.SixtyEight)]
    [TestCase(68, LoopEnumerationFactory.Numbers.SixtyNine)]
    [TestCase(69, LoopEnumerationFactory.Numbers.Seventy)]
    [TestCase(70, LoopEnumerationFactory.Numbers.SeventyOne)]
    [TestCase(71, LoopEnumerationFactory.Numbers.SeventyTwo)]
    [TestCase(72, LoopEnumerationFactory.Numbers.SeventyThree)]
    [TestCase(73, LoopEnumerationFactory.Numbers.SeventyFour)]
    [TestCase(74, LoopEnumerationFactory.Numbers.SeventyFive)]
    [TestCase(75, LoopEnumerationFactory.Numbers.SeventySix)]
    [TestCase(76, LoopEnumerationFactory.Numbers.SeventySeven)]
    [TestCase(77, LoopEnumerationFactory.Numbers.SeventyEight)]
    [TestCase(78, LoopEnumerationFactory.Numbers.SeventyNine)]
    [TestCase(79, LoopEnumerationFactory.Numbers.Eighty)]
    [TestCase(80, LoopEnumerationFactory.Numbers.EightyOne)]
    [TestCase(81, LoopEnumerationFactory.Numbers.EightyTwo)]
    [TestCase(82, LoopEnumerationFactory.Numbers.EightyThree)]
    [TestCase(83, LoopEnumerationFactory.Numbers.EightyFour)]
    [TestCase(84, LoopEnumerationFactory.Numbers.EightyFive)]
    [TestCase(85, LoopEnumerationFactory.Numbers.EightySix)]
    [TestCase(86, LoopEnumerationFactory.Numbers.EightySeven)]
    [TestCase(87, LoopEnumerationFactory.Numbers.EightyEight)]
    [TestCase(88, LoopEnumerationFactory.Numbers.EightyNine)]
    [TestCase(89, LoopEnumerationFactory.Numbers.Ninety)]
    [TestCase(90, LoopEnumerationFactory.Numbers.NinetyOne)]
    [TestCase(91, LoopEnumerationFactory.Numbers.NinetyTwo)]
    [TestCase(92, LoopEnumerationFactory.Numbers.NinetyThree)]
    [TestCase(93, LoopEnumerationFactory.Numbers.NinetyFour)]
    [TestCase(94, LoopEnumerationFactory.Numbers.NinetyFive)]
    [TestCase(95, LoopEnumerationFactory.Numbers.NinetySix)]
    [TestCase(96, LoopEnumerationFactory.Numbers.NinetySeven)]
    [TestCase(97, LoopEnumerationFactory.Numbers.NinetyEight)]
    [TestCase(98, LoopEnumerationFactory.Numbers.NinetyNine)]
    [TestCase(99, LoopEnumerationFactory.Numbers.OneHundred)]
    public void CreateLoopEnumeration_ReturnsArrayInCorrectOrder(int position, int expectedValue)
    {
        var values = _cut.CreateLoopEnumeration().ToArray();

        Assert.That(values[position], Is.EqualTo(expectedValue));
    }

    [TestCase(1, LoopEnumerationFactory.Numbers.One)]
    [TestCase(2, LoopEnumerationFactory.Numbers.Two)]
    [TestCase(3, LoopEnumerationFactory.Numbers.Three)]
    [TestCase(4, LoopEnumerationFactory.Numbers.Four)]
    [TestCase(5, LoopEnumerationFactory.Numbers.Five)]
    [TestCase(6, LoopEnumerationFactory.Numbers.Six)]
    [TestCase(7, LoopEnumerationFactory.Numbers.Seven)]
    [TestCase(8, LoopEnumerationFactory.Numbers.Eight)]
    [TestCase(9, LoopEnumerationFactory.Numbers.Nine)]
    [TestCase(10, LoopEnumerationFactory.Numbers.Ten)]
    [TestCase(11, LoopEnumerationFactory.Numbers.Eleven)]
    [TestCase(12, LoopEnumerationFactory.Numbers.Twelve)]
    [TestCase(13, LoopEnumerationFactory.Numbers.Thirteen)]
    [TestCase(14, LoopEnumerationFactory.Numbers.Fourteen)]
    [TestCase(15, LoopEnumerationFactory.Numbers.Fifteen)]
    [TestCase(16, LoopEnumerationFactory.Numbers.Sixteen)]
    [TestCase(17, LoopEnumerationFactory.Numbers.Seventeen)]
    [TestCase(18, LoopEnumerationFactory.Numbers.Eighteen)]
    [TestCase(19, LoopEnumerationFactory.Numbers.Nineteen)]
    [TestCase(20, LoopEnumerationFactory.Numbers.Twenty)]
    [TestCase(21, LoopEnumerationFactory.Numbers.TwentyOne)]
    [TestCase(22, LoopEnumerationFactory.Numbers.TwentyTwo)]
    [TestCase(23, LoopEnumerationFactory.Numbers.TwentyThree)]
    [TestCase(24, LoopEnumerationFactory.Numbers.TwentyFour)]
    [TestCase(25, LoopEnumerationFactory.Numbers.TwentyFive)]
    [TestCase(26, LoopEnumerationFactory.Numbers.TwentySix)]
    [TestCase(27, LoopEnumerationFactory.Numbers.TwentySeven)]
    [TestCase(28, LoopEnumerationFactory.Numbers.TwentyEight)]
    [TestCase(29, LoopEnumerationFactory.Numbers.TwentyNine)]
    [TestCase(30, LoopEnumerationFactory.Numbers.Thirty)]
    [TestCase(31, LoopEnumerationFactory.Numbers.ThirtyOne)]
    [TestCase(32, LoopEnumerationFactory.Numbers.ThirtyTwo)]
    [TestCase(33, LoopEnumerationFactory.Numbers.ThirtyThree)]
    [TestCase(34, LoopEnumerationFactory.Numbers.ThirtyFour)]
    [TestCase(35, LoopEnumerationFactory.Numbers.ThirtyFive)]
    [TestCase(36, LoopEnumerationFactory.Numbers.ThirtySix)]
    [TestCase(37, LoopEnumerationFactory.Numbers.ThirtySeven)]
    [TestCase(38, LoopEnumerationFactory.Numbers.ThirtyEight)]
    [TestCase(39, LoopEnumerationFactory.Numbers.ThirtyNine)]
    [TestCase(40, LoopEnumerationFactory.Numbers.Forty)]
    [TestCase(41, LoopEnumerationFactory.Numbers.FortyOne)]
    [TestCase(42, LoopEnumerationFactory.Numbers.FortyTwo)]
    [TestCase(43, LoopEnumerationFactory.Numbers.FortyThree)]
    [TestCase(44, LoopEnumerationFactory.Numbers.FortyFour)]
    [TestCase(45, LoopEnumerationFactory.Numbers.FortyFive)]
    [TestCase(46, LoopEnumerationFactory.Numbers.FortySix)]
    [TestCase(47, LoopEnumerationFactory.Numbers.FortySeven)]
    [TestCase(48, LoopEnumerationFactory.Numbers.FortyEight)]
    [TestCase(49, LoopEnumerationFactory.Numbers.FortyNine)]
    [TestCase(50, LoopEnumerationFactory.Numbers.Fifty)]
    [TestCase(51, LoopEnumerationFactory.Numbers.FiftyOne)]
    [TestCase(52, LoopEnumerationFactory.Numbers.FiftyTwo)]
    [TestCase(53, LoopEnumerationFactory.Numbers.FiftyThree)]
    [TestCase(54, LoopEnumerationFactory.Numbers.FiftyFour)]
    [TestCase(55, LoopEnumerationFactory.Numbers.FiftyFive)]
    [TestCase(56, LoopEnumerationFactory.Numbers.FiftySix)]
    [TestCase(57, LoopEnumerationFactory.Numbers.FiftySeven)]
    [TestCase(58, LoopEnumerationFactory.Numbers.FiftyEight)]
    [TestCase(59, LoopEnumerationFactory.Numbers.FiftyNine)]
    [TestCase(60, LoopEnumerationFactory.Numbers.Sixty)]
    [TestCase(61, LoopEnumerationFactory.Numbers.SixtyOne)]
    [TestCase(62, LoopEnumerationFactory.Numbers.SixtyTwo)]
    [TestCase(63, LoopEnumerationFactory.Numbers.SixtyThree)]
    [TestCase(64, LoopEnumerationFactory.Numbers.SixtyFour)]
    [TestCase(65, LoopEnumerationFactory.Numbers.SixtyFive)]
    [TestCase(66, LoopEnumerationFactory.Numbers.SixtySix)]
    [TestCase(67, LoopEnumerationFactory.Numbers.SixtySeven)]
    [TestCase(68, LoopEnumerationFactory.Numbers.SixtyEight)]
    [TestCase(69, LoopEnumerationFactory.Numbers.SixtyNine)]
    [TestCase(70, LoopEnumerationFactory.Numbers.Seventy)]
    [TestCase(71, LoopEnumerationFactory.Numbers.SeventyOne)]
    [TestCase(72, LoopEnumerationFactory.Numbers.SeventyTwo)]
    [TestCase(73, LoopEnumerationFactory.Numbers.SeventyThree)]
    [TestCase(74, LoopEnumerationFactory.Numbers.SeventyFour)]
    [TestCase(75, LoopEnumerationFactory.Numbers.SeventyFive)]
    [TestCase(76, LoopEnumerationFactory.Numbers.SeventySix)]
    [TestCase(77, LoopEnumerationFactory.Numbers.SeventySeven)]
    [TestCase(78, LoopEnumerationFactory.Numbers.SeventyEight)]
    [TestCase(79, LoopEnumerationFactory.Numbers.SeventyNine)]
    [TestCase(80, LoopEnumerationFactory.Numbers.Eighty)]
    [TestCase(81, LoopEnumerationFactory.Numbers.EightyOne)]
    [TestCase(82, LoopEnumerationFactory.Numbers.EightyTwo)]
    [TestCase(83, LoopEnumerationFactory.Numbers.EightyThree)]
    [TestCase(84, LoopEnumerationFactory.Numbers.EightyFour)]
    [TestCase(85, LoopEnumerationFactory.Numbers.EightyFive)]
    [TestCase(86, LoopEnumerationFactory.Numbers.EightySix)]
    [TestCase(87, LoopEnumerationFactory.Numbers.EightySeven)]
    [TestCase(88, LoopEnumerationFactory.Numbers.EightyEight)]
    [TestCase(89, LoopEnumerationFactory.Numbers.EightyNine)]
    [TestCase(90, LoopEnumerationFactory.Numbers.Ninety)]
    [TestCase(91, LoopEnumerationFactory.Numbers.NinetyOne)]
    [TestCase(92, LoopEnumerationFactory.Numbers.NinetyTwo)]
    [TestCase(93, LoopEnumerationFactory.Numbers.NinetyThree)]
    [TestCase(94, LoopEnumerationFactory.Numbers.NinetyFour)]
    [TestCase(95, LoopEnumerationFactory.Numbers.NinetyFive)]
    [TestCase(96, LoopEnumerationFactory.Numbers.NinetySix)]
    [TestCase(97, LoopEnumerationFactory.Numbers.NinetySeven)]
    [TestCase(98, LoopEnumerationFactory.Numbers.NinetyEight)]
    [TestCase(99, LoopEnumerationFactory.Numbers.NinetyNine)]
    [TestCase(100, LoopEnumerationFactory.Numbers.OneHundred)]
    public void CreateLoopEnumeration_ValueAreCorrect(int value, int expectedValue)
    {
        Assert.That(value, Is.EqualTo(expectedValue));
    }
}